### PR TITLE
docs: repo rate badge

### PR DESCRIPTION
**Pull request by eddiejaoude**
- display latest rating
- clickable badge for people to vote

### CODE REVIEW

**Review by Giuliano1993 — APPROVED** [review]
Definitely needed that repo-rater badge! Thank you @eddiejaoude !

**Comment by CoderBlee** [comment]
I cant wait to get the repo-rater badge! @eddiejaoude  thank you

**Comment by eddiejaoude** [comment]
> I cant wait to get the repo-rater badge! @eddiejaoude thank you

thank you 👍

**Comment by Santa116** [comment]
necessary and important function. thank you

**Pull request merged**
